
#credits

import time

def credits():
    print("\n\n\n\t\t\t\tCREDITS\n\n\n")
    time.sleep(2)
    print("                        ________________________________         ")
    print("                       /________________________________\\       ")
    print("                       |    |    |    |    |  _____  |  |       ")
    print("                       |____|____|____|____| |  |  | |__|       ")
    print("                       | Author: Kieran Coe  |  |  |    |       ")
    print("                       |_____________________|__|__|____|       ")
    print("                   -------|_|__|-----------------|_|__|---------")
    print("\n")
    print("                    --  --  --  --  --  --  --  --  --  --  --  ")
    print("\n")
    print("                   ---------------------------------------------")
    time.sleep(6)
    print("\n\n\n\t\t\t\tMUSIC")
    print("\n\n\n")
    time.sleep(2)
    print("\t               ____              ______------____           ")
    print("\t      _______--    -----____    -________________------     ")
    print("\t      -----_____________----                                ")
    print("\t\n\n\n\n\n\n\n")
    print("\t        Out of Time               o                         ")
    print("\t        Rajat Tiwari             //                         ")
    print("\t                                 //                         ")
    time.sleep(6)
    print("\n\n\n")
    print("\t\t      __     Deer Hunter's      _   ")
    print("\t\t     |  |_     Anthem          /_|  ")
    print("\t\t     (oo) _____         /-----//    ")
    print("\t\t     |  ||_/           /|_____/     ")
    print("\t\t     |__|    Jeff Hunt  |    |      ")
    print("\t\t   __/__/               |    |      ")
    print("\t\t^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
    time.sleep(6)
    print("\n\n\n")
    print("\t\t _____________________                              ")
    print("\t\t[   / \\*/ \\  / \\ */ \\ ]                         ")
    print("\t\t[ * --- -*-  --*  --- ]        milk cassete x.mp3   ")
    print("\t\t[   *|   |*   | *  | *]                             ")
    print("\t\t[  * |   |    |*   |  ]          analog_mannequin   ")
    print("\t\t[^^*^^^^^^*^^^*^^^^^^^]                             ")
    print("\t\t[__*_______*______*___]                             ")
    time.sleep(6)
    print("\n\n\n")
    print("\t\t   Science    --             ")
    print("\t\t   Base      /oo\\           ")
    print("\t\t         |  /    \\   Ben    ")
    print("\t\t         ---|    |   Tracta  ")
    print("\t\t         |  |    |           ")
    print("\t\t         |  ......           ")
    time.sleep(6)
    print("\n\n\n")
    print("\t\t                         _________         ")
    print("\t\t    _______________     |         |        ")
    print("\t\t   /               \\    | Costal  |        ")
    print("\t\t  /_________________\\   | Drive   |        ")
    print("\t\t   |               |    |_________|        ")
    print("\t\t   |    _     _    |        ||             ")
    print("\t\t   |   | |   |_|   |        ||  ADMO       ")
    print("\t\t   |___|_|_________|        ||             ")
    print("\t\t-------------------------------------------")
    print("\n")
    print("\t\t --  --  --  --  --  --  --  --  --  --  --")
    print("\n")
    print("\t\t-------------------------------------------")
    time.sleep(6)
    print("\n\n\n\t\t\t\tACTORS")
    print("\n\n\n")
    time.sleep(2)
    print("\t\tJason Wick...............Kieran Coe\n")
    time.sleep(2)
    print("\t\tCarol McClain............Lydia Velazquez\n")
    time.sleep(2)
    print("\t\tDave Peters..............Dave Tallett\n")
    time.sleep(2)
    print("\t\tPhillip Andrews..........Caleb Pacha\n")
    time.sleep(2)
    print("\t\tMary Heart...............Helen Coe\n")
    time.sleep(2)
    print("\t\tAntonio Garcia...........Alvero Velazquez\n")
    time.sleep(2)
    print("\t\tLily Turner..............Claudia Velazquez\n")
    time.sleep(6)
    print("\n\n\n\t\t\t\tPLAYTESTERS")
    print("\n\n\n")
    time.sleep(2)
    print("\t\tYour name here!!!!")
    time.sleep(6)
    print("\n\n\t\t\t\tSPECIAL THANKS\n\n\n")
    time.sleep(2)
    print("\t\tBrady Christiansen\n")
    time.sleep(2)
    print("\t\t\tMason Price\n")
    time.sleep(2)
    print("\t\t\t\tBen Tracta\n")
    time.sleep(2)
    print("\t\t\t\t\tAndrew Farrell\n")
    time.sleep(2)
    print("\t\t\t\t\t\tRiley Mulvey\n")
    time.sleep(2)
    print("\t\t\t\t\t\t\t...and YOU!\n")
    time.sleep(6)
    print("\n\n\n\t\t\t\tTHANKS FOR PLAYING!")
    time.sleep(2)










    
