
#credits

import time

def credits():
    print("\n\n\n\t\t\t\tCREDITS\n\n\n")
    time.sleep(2)
    print("                        ________________________________         ")
    print("                       /________________________________\\       ")
    print("                       |    |    |    |    |  _____  |  |       ")
    print("                       |____|____|____|____| |  |  | |__|       ")
    print("                       | Author: Kieran Coe  |  |  |    |       ")
    print("                       |_____________________|__|__|____|       ")
    print("                   -------|_|__|-----------------|_|__|---------")
    print("\n")
    print("                    --  --  --  --  --  --  --  --  --  --  --  ")
    print("\n")
    print("                   ---------------------------------------------")
    time.sleep(6)
    print("\n\n\n\t\t\t\tMUSIC")
    time.sleep(2)
    print("\n\n")
    print("\t               ____              ______------____           ")
    print("\t      _______--    -----____    -________________------     ")
    print("\t      -----_____________----                                ")
    print("\t\n\n\n\n\n\n\n")
    print("\t        Out of Time               o                         ")
    print("\t        Rajat Tiwari             //                         ")
    print("\t                                 //                         ")
    time.sleep(6)
    print("\n\n\n")
    print("\t\t      __     Deer Hunter's      _   ")
    print("\t\t     |  |_     Anthem          /_|  ")
    print("\t\t     (oo) _____         /-----//    ")
    print("\t\t     |  ||_/           /|_____/     ")
    print("\t\t     |__|    Jeff Hunt  |    |      ")
    print("\t\t   __/__/               |    |      ")
    print("\t\t^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
    time.sleep(6)
    print("\n\n\n")
    print("\t\t _____________________                              ")
    print("\t\t[   / \\*/ \\  / \\ */ \\ ]                         ")
    print("\t\t[ * --- -*-  --*  --- ]        milk cassete x.mp3   ")
    print("\t\t[   *|   |*   | *  | *]                             ")
    print("\t\t[  * |   |    |*   |  ]          analog_mannequin   ")
    print("\t\t[^^*^^^^^^*^^^*^^^^^^^]                             ")
    print("\t\t[__*_______*______*___]                             ")
    time.sleep(6)
    print("\n\n\n")
    print("\t\t   Science    --             ")
    print("\t\t   Base      /oo\\           ")
    print("\t\t         |  /    \\   Ben    ")
    print("\t\t         ---|    |   Tracta  ")
    print("\t\t         |  |    |           ")
    print("\t\t         |  ......           ")
    time.sleep(6)
    print("\n\n\n")
    print("\t\t                         _________         ")
    print("\t\t    _______________     |         |        ")
    print("\t\t   /               \\    | Costal  |        ")
    print("\t\t  /_________________\\   | Drive   |        ")
    print("\t\t   |               |    |_________|        ")
    print("\t\t   |    _     _    |        ||             ")
    print("\t\t   |   | |   |_|   |        ||  ADMO       ")
    print("\t\t   |___|_|_________|        ||             ")
    print("\t\t-------------------------------------------")
    print("\n")
    print("\t\t --  --  --  --  --  --  --  --  --  --  --")
    print("\n")
    print("\t\t-------------------------------------------")
    time.sleep(6)
    print("\n\n\n\t\t\t\tACTORS")
    print("\n\n")
    print("\t\tJason Wick...............Kieran Coe")
    print("\t\tCarol McClain............Lydia Velazquez")
    print("\t\tDave Peters..............Dave Tallett")
    print("\t\tPhillip Andrews..........Caleb Pacha")
    print("\t\tMary Heart...............Helen Coe")
    print("\t\tAntonio Garcia...........Alvero Velazquez")
    print("\t\tLily Turner..............Claudia Velazquez")
    time.sleep(6)
    print("\n\n\n\t\t\t\tPLAYTESTERS")
    print("\n\n\n")
    print("\t\tYour name here!!!!")
    time.sleep(6)
    print("\n\n\t\t\t\tSPECIAL THANKS\n\n\n")
    print("\t\tBrady Christiansen")
    print("\t\tFaith Cequena")
    print("\t\tBen Tracta")
    print("\t\tAndrew and Riley")
    print("\t\t...and YOU!")
    time.sleep(6)
    print("\n\n\n\t\t\t\tTHANKS FOR PLAYING!")










    
